name = "nif-nome-api"
main = "src/index.ts"
compatibility_date = "2026-08-25"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "nif-nome"
database_id = "d300a891-5791-4a26-9204-cd962507c911"
migrations_dir = "migrations"
